import type { BankRow } from "./types";

export const MOCK_BANKS: BankRow[] = [
  {
    id: "bank-1",
    name: "Banco de Chile",
    code: "BDECH",
    accounts: [
      {
        id: "acc-1",
        bank_id: "bank-1",
        account_number: "001-123456-01",
        account_name: "Cuenta Corriente Principal",
        currency: "CLP",
        statement_balance: 45_230_500,
        accounting_balance: 44_980_200,
        difference: 250_300,
        transactions_total: 124,
        transactions_reconciled: 98,
        transactions_pending: 26,
        last_import_date: "2026-05-15",
        accounting_account_code: "1110",
        accounting_account_name: "Banco de Chile CTE",
      },
      {
        id: "acc-2",
        bank_id: "bank-1",
        account_number: "001-789012-02",
        account_name: "Cuenta USD Exportaciones",
        currency: "USD",
        statement_balance: 12_450.75,
        accounting_balance: 12_450.75,
        difference: 0,
        transactions_total: 31,
        transactions_reconciled: 31,
        transactions_pending: 0,
        last_import_date: "2026-05-14",
        accounting_account_code: "1115",
        accounting_account_name: "Banco de Chile USD",
      },
    ],
  },
  {
    id: "bank-2",
    name: "BCI",
    code: "BCI",
    accounts: [
      {
        id: "acc-3",
        bank_id: "bank-2",
        account_number: "023-456789-03",
        account_name: "Cuenta Corriente Operaciones",
        currency: "CLP",
        statement_balance: 18_750_000,
        accounting_balance: 17_200_000,
        difference: 1_550_000,
        transactions_total: 87,
        transactions_reconciled: 65,
        transactions_pending: 22,
        last_import_date: "2026-05-13",
        accounting_account_code: "1120",
        accounting_account_name: "BCI CTE Operaciones",
      },
    ],
  },
  {
    id: "bank-3",
    name: "Santander",
    code: "SANT",
    accounts: [
      {
        id: "acc-4",
        bank_id: "bank-3",
        account_number: "072-654321-04",
        account_name: "Cuenta Corriente Proveedores",
        currency: "CLP",
        statement_balance: 8_320_400,
        accounting_balance: 8_320_400,
        difference: 0,
        transactions_total: 43,
        transactions_reconciled: 43,
        transactions_pending: 0,
        last_import_date: "2026-05-12",
        accounting_account_code: "1130",
        accounting_account_name: "Santander CTE Proveedores",
      },
    ],
  },
  {
    id: "bank-4",
    name: "Scotiabank",
    code: "SCOT",
    accounts: [
      {
        id: "acc-5",
        bank_id: "bank-4",
        account_number: "055-321654-05",
        account_name: "Cuenta Vista Caja Chica",
        currency: "CLP",
        statement_balance: 980_000,
        accounting_balance: 980_000,
        difference: 0,
        transactions_total: 12,
        transactions_reconciled: 12,
        transactions_pending: 0,
        last_import_date: "2026-05-10",
        accounting_account_code: "1105",
        accounting_account_name: "Scotiabank Vista",
      },
    ],
  },
];
